"""empty message

Revision ID: a41f7b719837
Revises:
Create Date: 2024-03-12 22:45:18.355939

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a41f7b719837"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tarkov_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("base_price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tarkov_items")
    # ### end Alembic commands ###
